return {
	{
		"folke/tokyonight.nvim",
		lazy = false,
		priority = 1000,
		opts = {},
	},
	{ "mhartington/formatter.nvim" },
	{ "m4xshen/autoclose.nvim" },
	{ "mhinz/vim-signify" },
	{ "f-person/git-blame.nvim" },
	{ "ms-jpq/chadtree" },
	{ "ryanoasis/vim-devicons" },
	{ "sheerun/vim-polyglot" },
	{ "neovim/nvim-lspconfig" },
	{ "hrsh7th/cmp-nvim-lsp" },
	{ "hrsh7th/cmp-buffer" },
	{ "hrsh7th/cmp-path" },
	{ "hrsh7th/cmp-cmdline" },
	{ "hrsh7th/nvim-cmp" },
	{ "hrsh7th/cmp-vsnip" },
	{ "hrsh7th/vim-vsnip" },
	{
		"nvim-lualine/lualine.nvim",
		dependencies = { "nvim-tree/nvim-web-devicons" },
	},
	{ "sindrets/diffview.nvim" },
}
